name: 'Terraform Deployment Pipeline'

on:
  push:
    branches:
      - qa
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Inicializar Terraform
      run: terraform init
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Detectar Entorno
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "ENV=prod" >> $GITHUB_ENV
        else
          echo "ENV=qa" >> $GITHUB_ENV
        fi

    - name: Terraform Apply
      run: terraform apply -var="environment=${{ env.ENV }}" -auto-approve
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}