name: 'Terraform CD Unified'

on:
  push:
    branches:
      - qa # Todo se ejecuta desde QA para no depender de la aprobación de main

jobs:
  terraform:
    name: 'Despliegue AWS Dual'
    runs-on: ubuntu-latest

    steps:
    - name: Copiar Codigo
      uses: actions/checkout@v3

    - name: Configurar Terraform
      uses: hashicorp/setup-terraform@v2

    # ==========================================================================
    # FRENTE 1: DESPLIEGUE EN LA CUENTA DE QA
    # ==========================================================================
    - name: Credenciales AWS - Entorno QA
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_QA }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_QA }}
        aws-region: us-east-1

    - name: Inicializar Terraform en QA
      run: |
        terraform init -input=false -backend-config="bucket=s3-smartcampus-uce-m4-qa" -backend-config="key=global/s3/terraform.tfstate" -backend-config="region=us-east-1"

    - name: Desplegar en QA
      run: |
        terraform workspace select qa || terraform workspace new qa
        terraform apply -auto-approve -var="environment=qa"

    # ==========================================================================
    # FRENTE 2: DESPLIEGUE EN LA CUENTA DE PRODUCCIÓN
    # ==========================================================================
    - name: Credenciales AWS - Entorno PROD
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_PROD }}
        aws-region: us-east-1

    # --- CORRECCIÓN EXTRA: Limpieza física de metadatos para olvidar el workspace "qa" ---
    - name: Inicializar Terraform en PROD
      run: |
        rm -rf .terraform .terraform.lock.hcl
        terraform init -input=false -backend-config="bucket=s3-smartcampus-uce-m4-prod" -backend-config="key=global/s3/terraform.tfstate" -backend-config="region=us-east-1"

    - name: Desplegar en PROD
      run: |
        terraform workspace select prod || terraform workspace new prod
        terraform apply -auto-approve -var="environment=prod"