name: 'Terraform CD - Entorno PROD'
on:
  push:
    branches: [ main ] # Se activa al hacer merge a la rama principal (Producción)

jobs:
  terraform-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Configurar Credenciales Lab PROD
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_PROD }}
        aws-region: us-east-1

    - name: Desplegar en PROD
      run: |
        cd prod
        terraform init -input=false
        terraform apply -auto-approve