name: 'Terraform CD'

on:
  push:
    branches:
      - qa
      - main

jobs:
  terraform:
    name: 'Despliegue AWS'
    runs-on: ubuntu-latest

    steps:
    - name: Copiar Codigo
      uses: actions/checkout@v3

    - name: Configurar Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Credenciales AWS - Entorno QA
      if: github.ref == 'refs/heads/qa'
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_QA }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_QA }}
        aws-region: us-east-1

    - name: Credenciales AWS - Entorno PROD
      if: github.ref == 'refs/heads/main'
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_PROD }}
        aws-region: us-east-1

    - name: Verificar identidad AWS
      if: github.ref == 'refs/heads/main'
      run: |
        aws sts get-caller-identity

    - name: Inicializar Terraform en QA
      if: github.ref == 'refs/heads/qa'
      run: |
        terraform init -backend-config="bucket=${{ secrets.S3_BUCKET_QA }}" -backend-config="key=global/s3/terraform.tfstate" -backend-config="region=us-east-1"

    - name: Inicializar Terraform en PROD
      if: github.ref == 'refs/heads/main'
      run: |
        terraform init -backend-config="bucket=${{ secrets.S3_BUCKET_PROD }}" -backend-config="key=global/s3/terraform.tfstate" -backend-config="region=us-east-1"

    - name: Desplegar en QA
      if: github.ref == 'refs/heads/qa'
      run: |
        terraform workspace select qa || terraform workspace new qa
        terraform apply -auto-approve -var="environment=qa"

    - name: Desplegar en PROD
      if: github.ref == 'refs/heads/main'
      run: |
        terraform workspace select prod || terraform workspace new prod
        terraform apply -auto-approve -var="environment=prod"